spring:
  application:
    name: aw-api-graphql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG