spring:
  application:
    name: aw-api-graphql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: "*"

    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      percentage: 1.0



server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG