spring:
  application:
    name: aw-api-graphql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
  zipkin:
    base-url: http://localhost:9411

  management:
    tracing:
      sampling:
        probability: 1.0  # 100% sampling for local testing

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG